markdown: kramdown
remote_theme: ankitsultana/researcher@gem

title: Christopher R. Iacovella
url: "chrisiacovella.github.io"
baseurl: "/home"

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
