markdown: kramdown
remote_theme: ankitsultana/researcher@gem

title: Christopher R. Iacovella
url: "chrisiacovella.github.io"
baseurl: "/docs/about.md"

nav:
 - name: "About"
   link: "/docs/about.md"
 - name: "Resume"
   link: "/docs/resume.md"
 - name: "Publications"
   link: "/docs/publications.md"
 - name: "Projects"
   link: "/docs/projects.md"
