markdown: kramdown

title: Christopher R. Iacovella
url: "chrisiacovella.github.io"
baseurl: "/docs/"

nav:
 - name: "About"
   link: "about.md"
 - name: "Resume"
   link: "resume.md"
 - name: "Publications"
   link: "publications.md"
 - name: "Projects"
   link: "projects.md"
